# Generated by Django 5.2.7 on 2025-10-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_purchase',
            new_name='buy_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_add',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
