# Generated by Django 5.2.7 on 2025-10-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_favorite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='http://localhost:9000/products/default.jpg', max_length=500, null=True),
        ),
    ]
