# Generated by Django 5.2.7 on 2025-11-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_like_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
