# Generated by Django 5.2.7 on 2025-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default='http://localhost:9000/avatars/default.jpg', max_length=500, null=True),
        ),
    ]
